version: "3.7"

networks:
  cover-network:
  
services:
  cover-web:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5289:80"
    environment:
        ASPNET_ENVIRONMENT: "Development"
    networks:
      - cover-network