version: "3.7"

networks:
  api-network:
  
services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5289:80"
    environment:
        ASPNET_ENVIRONMENT: "Development"
    networks:
      - api-network